name: 文件下载

on:
  # 手动触发
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
        mkdir upload
        wget -P ./upload/alist-windows-amd64.zip https://github.com/alist-org/alist/releases/download/v3.36.0/alist-windows-amd64.zip
        ls

    - name: 连接sftp服务器
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.AB_DEV_SERVER }}
        username: ${{ secrets.AB_DEV_SERVER_USER }}
        password: ${{ secrets.AB_DEV_SERVER_PASS }}
        port: ${{ secrets.AB_DEV_SERVER_PORT }}
        uploads: |
          ./upload => /upload/