name: Docker一键安装脚本下载

on:
  # 手动触发
  workflow_dispatch:
  schedule:
    - cron: '00 16 * * *'

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
         curl -o linux.sh "https://get.docker.com"
         mkdir shell
         cp linux.sh ./shell

    - name: 连接sftp服务器
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.AB_DEV_SERVER }}
        username: ${{ secrets.AB_DEV_SERVER_USER }}
        password: ${{ secrets.AB_DEV_SERVER_PASS }}
        port: ${{ secrets.AB_DEV_SERVER_PORT }}
        uploads: |
          ./shell/ => /upload/